global:
  scrape_interval: 15s 
  evaluation_interval: 15s

scrape_configs:
  
  - job_name: aggregated-trace-metrics
    static_configs:
    - targets: ['otel-collector:8889']
  
  - job_name: otelcol-internal
    static_configs:
    - targets: ['otel-collector:8888']
    
  - job_name: 'cassandra'
    static_configs:
      - targets: ['cassandra:7070']

